### ISSUE TITLE
homeSlug does not seem to be working

### ISSUE THREAD

**Issue by tlambrou** [storyblok/gatsby-source-storyblok#11]
I was not able to get the `homeSlug` option to work.  Instead I had to resort to minor hack to get this to work.

**Comment by emanuelgsouza** [comment]
Hi, thanks for submitting this issue and sorry for the late response. Well, this option was removed in the latest version of this package ([v1.0.0](https://github.com/storyblok/gatsby-source-storyblok/tree/v1.0.0)). You can handle with the root story (usually called `Home`) when you create the pages in `gatsby-node.js` like we describe in some of our demo repositories (for example in [here](https://github.com/storyblok/gatsby-storyblok-boilerplate/blob/8b81a663c9698352b324c9d5b0db61604e356c79/gatsby-node.js#L41-L58))
