### ISSUE TITLE
Example of resolveRelations?

### ISSUE THREAD

**Issue by kelenakamura** [storyblok/gatsby-source-storyblok#12]
Sorry trying to resolve relations but not sure what is supposed to be returned when this is enabled.

Basically have articles with a relationship to authors, so ideally when retrieving articles, or an article, we can get the author name that has been related to that article.

**Comment by NikkiJonesR** [comment]
Resolve relation keys within Gatsby correspond with Storyblok's components. These associate with field_component in GraphQL.

For ex. to retrieve author data from another post within your post the gatsby-config would look something like this:
```
{
      resolve: 'gatsby-source-storyblok',
      options: {
        accessToken: '###',
        homeSlug: 'home',
        version: 'draft',
        resolveRelations: ["my_post_name.author"],
      }
    },
```
Where my_post_name is the name of the component, and author is the name of the author field within the my_post_name schema.

To query the data:
```
{
  allStoryblokEntry(filter: {field_component: {eq: "my_post_name"}}) {
    edges {
      node {
        content
      }
    }
  }
}

The content node will contain a stringified object including the author object with its own related data.

**Comment by emanuelgsouza** [comment]
Hi! Thanks for submitting this issue @kelenakamura and thanks @NikkiJonesR for your answer. We'll update the documentation with this example!
