### ISSUE TITLE
Why are Objects and Arrays Stringified? -- Can't properly access data in GraphQL query

### ISSUE THREAD

**Issue by michelesketchin** [storyblok/gatsby-source-storyblok#13]
Hi,
I'm encountering a problem when I need to query data such as Objects and Arrays.

At line `34` of the plugin's `gatsby-node.js` is written:

https://github.com/storyblok/gatsby-source-storyblok/blob/185a8b67f8ea54b2ba5305247f57671e845e81dd/gatsby-node.js#L34

That creates the schema for **fields_** such as `fields_fieldname_string`, `fields_fieldname_number`, `fields_fieldname_boolean`. 

I need to access other types of fields such as `field_fieldname_array` and `field_fieldname_object` that are present inside the stringified content but not in the **fields_** schema

I overcame this limitations by adding to the IF statement before, two more values to the array, in order to add that functionality in the plugin.

I can't find why this solutions is not provided by default, and if you are going to add it. It is needed. 

Another question is: why do you stringify those types? What are the rationals behind? 

Thx

**Comment by onefriendaday** [comment]
The reason of stringifying those types is because Gatsby doesn't allow a JSON type.

See following issue in Gatsby:
https://github.com/gatsbyjs/gatsby/issues/8142#issuecomment-423832748

Gridsome, the equivalent framework in the Vue.js world has this type (See https://github.com/storyblok/gridsome-source-storyblok/blob/master/utils/create-schema.js#L21) so maybe opening an issue on Gatsby or making a PR on their repository will help us doing it without needing to encode the JSON to a string.

**Comment by michelesketchin** [comment]
Thanks,
so you are saying, accordingly to Gatsby documentation, that is not possibile to replicate the GraphQL schema I get on the `http://gapi-browser.storyblok.com/`playground.

Example of my query and schema is:
<img width="1652" alt="Schermata 2019-11-06 alle 08 16 27" src="https://user-images.githubusercontent.com/20659387/68276926-6474cc00-006e-11ea-87c6-565e6fc3d9a9.png">

So every kind of pre-selection I did, because I'll get only the stringified content, I will have to do it manually in the gatsby-node file, am I right?

**Comment by amykapernick** [comment]
Not sure if something has changed since this was first opened, but I just had a look at running this plugin locally in my Gatsby install and commenting out line 42 of `gatsby-node.js`, it still processes the data and it now makes all the content available via GraphQl and hasn't resulted in any errors.

Is this likely to cause issues with other data types other than my specific setup?

<https://github.com/storyblok/gatsby-source-storyblok/blob/master/gatsby-node.js#L42>
```
await Sync.getAll('stories', {
      node: 'StoryblokEntry',
      params: getStoryParams(language, options),
      process: (item) => {
        for (var prop in item.content) {
          console.log(item)
          if (!item.content.hasOwnProperty(prop) || ['_editable', '_uid'].indexOf(prop) > -1) {
            continue;
          }
          const objectType = Object.prototype.toString.call(item.content[prop])
                                                      .replace('[object ', '')
                                                      .replace(']', '')
                                                      .toLowerCase()

          if (['number', 'boolean', 'string'].indexOf(objectType) === -1) {
            continue;
          }

          const type = prop == 'component' ? '' : ('_' + objectType)

          item['field_' + prop + type] = item.content[prop]
        }
        // item.content = stringify(item.content)
      }
    })
```

**Comment by darkowic** [comment]
This is really a major problem blocking common usages like displaying a preview of blog posts. In the official gatsby blog post https://www.storyblok.com/tp/gatsby-multilanguage-website-tutorial#build-a-multilanguage-navigation you fetch all blog posts and then filter is JS only few you need to just display preview... https://github.com/storyblok/gatsbyjs-multilanguage-website/blob/master/src/components/ArticleTeaser.js
```js
  const { articles, authors } = useStaticQuery(graphql`
  query Articles {
    articles: allStoryblokEntry(filter: {field_component: {eq: "blogpost"}}) {
      edges {
        node {
          name
          full_slug
          content
        }
      }
    }
...
let article = articles.edges.filter(({ node }) => node.full_slug === blok.article.cached_url)
```

The desired solution would be to have the ability to fetch items data like this:
```
query HomePage {
  featuredBlogPosts { // this is the multi options stories entry
    name
}
}
```

cc @lisilinhart

**Comment by renet** [comment]
@amykapernick's perfectly works for me. Can @onefriendaday or somebody else from Storyblok please give a statement on whether this can become a pull request or if there are any issues with this?

Especially as v2.0.0 has just been released a few days ago, such a breaking change would have perfectly fit into it.

**Comment by onefriendaday** [comment]
Commenting out "item.content = stringify(item.content)" will lead to problems when you use a file type with the same name in multiple content types with different types. It will throw an error at the build.

**Comment by renet** [comment]
I understand. [Inline Fragments](https://graphql.org/learn/queries/#inline-fragments) will probably help with that. If I find the time, I will work on a PR for this...

**Comment by joakimmillen** [comment]
@onefriendaday could you give a more specific case where it fails? Based on your description I've tried to recreate the issue but can't. Thanks!

**Comment by Patrickodey360coder** [comment]
Hello @michelesketchin are you still having problems with this?

**Comment by Patrickodey360coder** [comment]
feel free to re-open this issue if it’s still on going
