### ISSUE TITLE
Error: Request failed with status code 401

### ISSUE THREAD

**Issue by raqibjs** [storyblok/gatsby-source-storyblok#137]
I have tried both GatsbyJS and NextJS boilerplate also. The same thing happening, 401 error! I want to use Storyblok as my go-to Headless CMS for all the clients, But now I am feeling hopeless about it! 

![image](https://user-images.githubusercontent.com/11327451/194474503-30210807-c0da-431e-a530-3383904f1cc7.png)

Pls, help @spences10 @onefriendaday @jonsuh @fgiuliani @saijim

**Comment by raqibjs** [comment]
I have pointed out the issue. The space server location was "US". It causing the issue. The "EU" server working fine!

**If you want to select the US server. You do have to specify the "us" region specifically in the gatsby-config.js file.**

```
options: {
        accessToken: process.env.GATSBY_STORYBLOK_ACCESS_TOKEN,
        ....
        ....
        region: 'us'  // <<------------------ Add this line
      }
```

**Comment by raqibjs** [comment]
I have pointed out the issue. The space server location was "US". It causing the issue. The "EU" server working fine!

If you want to select the US server. You do have to specify the "us" region specifically in the gatsby-config.js file.

options: {
        accessToken: process.env.GATSBY_STORYBLOK_ACCESS_TOKEN,
        ....
        ....
        region: 'us'  // <<------------------ Add this line
      }

**Comment by pak11273** [comment]
@raqibjs took me 5 days of digging around and if you hadn't of posted this I would have been lost for who knows how much longer.  The docs are still not updated to remedy this error or perhaps I'm just missing something.  In any case thanks!
