### ISSUE TITLE
What's the correct way to retrieve all the dimensions from datasources via graphQL?

### ISSUE THREAD

**Issue by dmnplb** [storyblok/gatsby-source-storyblok#14]
Hi,
I'm trying to get all the dimensions from a specific datasource via graphQL, but when I try to access the `dimensions` field, I get `null` values.

I attach an example of query I'm using in the graphQL Explorer:
```
allStoryblokDatasource(filter: {data_source: {eq: "cta"}}) {
    edges {
      node {
        id
        name
        value
        dimensions {
          name
          id
          entry_value
        }
      }
    }
  }
```

**Comment by sharanrprasad** [comment]
We are facing the same issue as well

**Comment by emanuelgsouza** [comment]
Hi, thanks for submitting this issue and sorry for delay. So, it was implemented a fix for that. When it's merged, I'll report on this issue.

**Comment by emanuelgsouza** [comment]
The fix is already published. Take a look on the [v1.1.0](https://github.com/storyblok/gatsby-source-storyblok/releases/tag/v1.1.0) version.

You can check the README about that.
