### ISSUE TITLE
Possible bug in `onCreateNode` when using local assets

### ISSUE THREAD

**Issue by alex-mcgovern** [storyblok/gatsby-source-storyblok#142]
Greetings 👋

While poking around in your source code, I noticed what looks like a small bug.

In `gatsby-node`, in `onCreateNode`, when `localAssets` is enabled, it calles `getCache()` with a cache key, then starts using it like it's a cached item. In actuality I think it should be calling `cache.get()`, and suspect that assets aren't being cached at all.

I'm not currently using `localAssets`, so this doesn't affect me. I don't have the time to open a PR right now, but flagging for investigation, and if I have time I'll try to get to it myself. I might be wrong, but I've built a similar, smaller plugin, and using `getCache()` like this will throw a type error.

https://github.com/storyblok/gatsby-source-storyblok/blob/1c14515e33a0b80619b1a4c7a6d6dcf9756a3ecb/lib/gatsby-node.js#L119

Current:
```js
      imagePaths.forEach(async (imagePath) => {
        // ...
        const cacheMediaData = await getCache(mediaDataCacheKey); // <- `getCache` returns object of type `GatsbyCache`, not cached item
        // ...
      });
```

What I think it should be:
```js
      imagePaths.forEach(async (imagePath) => {
        // ...
        const cacheMediaData = await cache.get(mediaDataCacheKey); 
        // ...
      });

**Comment by schabibi1** [comment]
@alex-mcgovern I'll close this issue for now as we see the numbers of downloading Gatsby SDK is decreasing and the technology itself is not on the rise.
Please feel free to re-open this issue if you face any urgent blockers.
