### ISSUE TITLE
All storyblok data getting exported into final build javascript bundle

### ISSUE THREAD

**Issue by brtdwchtr** [storyblok/gatsby-source-storyblok#15]
Hey guys, 

I'm not sure if this expected behaviour, doesn't feel like it. We're running into an issue with our site running on Storyblok and Gatsby. Looks like all storyblok data is getting exported as a module into the final javascript file. For our site that's a major problem since it ends up being a file of 5MB (25MB uncompressed).

I have been searching high and low to understand where this happens, but can't find it.
Example of such a js file that gets generated: https://www.svk.be/2-4468f4f756272b6ad09f.js

*EDIT*
Visualizing the sourcemap for this file reveals this:
https://cl.ly/61e96877cf73
Having a hard time figuring out why that file would represent such an enormous amount of data though.

**Comment by onefriendaday** [comment]
Maybe this helps:
https://www.gatsbyjs.org/blog/2019-06-12-performance-improvements-for-large-sites/

Can you provide more details about the implementation? Static Queries used, ...
