### ISSUE TITLE
README.md is not up to date, accurate or user friendly

### ISSUE THREAD

**Issue by ghost** [storyblok/gatsby-source-storyblok#153]
Some examples in the README reference functions/hooks that are not explained anywhere else in the document.

e.g. [this example usage of `useStoryblok`](https://github.com/storyblok/gatsby-source-storyblok/blob/e587e8098d9e08448bf02ee8247ba555d99c3490/README.md?plain=1#L180) has not been previously mentioned on the page, and in the context of the previous section, doesn't make sense. It is only mentioned once on the page.

```js
useStoryblok(story.internalId, (newStory) => setStory(newStory), {
  resolveRelations: ["Article.author"],
});
```

e.g. [this section explaining an alternative to `useStoryblokBridge`](https://github.com/storyblok/gatsby-source-storyblok/blob/e587e8098d9e08448bf02ee8247ba555d99c3490/README.md?plain=1#L273) is mentioned, but `useStoryblokBridge` hasn't been previously mentioned on the page, and in the context of the previous section, doesn't make sense. It is also only mentioned once in the document.

> If you don't use `useStoryblokBridge`, you still have access to the raw `window.StoryblokBridge`:

```js
const sbBridge = new window.StoryblokBridge(options);
sbBridge.on(["input", "published", "change"], (event) => {
  // ...
});
```

Overall, this gives the impression that the current README has been made up of copy/pasted chunks from new releases to other packages, without being read end-to-end and checked that it still makes sense.

---

## Expected Behavior

- When a function/hook is mentioned in the README, the reader should have context on why it is mentioned and it's relevance.
- It should be clear what is behaviour of vanilla `@storyblok/react` or `storyblok-js-client` vs extended functionality of `gatsby-source-storyblok`. 
- Finally, users should not have to compile and parse snippets from `@storyblok/react` or `storyblok-js-client` in order to make sense of the README for `gatsby-source-storyblok`

## Current Behavior

Inverse of above

## Steps to Reproduce

N/A, issue with README

**Comment by alex-mcgovern** [comment]
All feedback is objective, with much love for the team behind storyblok's js packages. It is just not currently documented correctly. ❤️

**Comment by schabibi1** [comment]
Hello, I hope our current README is now up to date and please feel free to let us know if you spot something not updated. Thanks for letting us know
