### ISSUE TITLE
Gatsby Build: Parse Error On Resolve Relation

### ISSUE THREAD

**Issue by michelesketchin** [storyblok/gatsby-source-storyblok#16]
Hello, 
I'm getting a parsing error when I `gatsby build` my gatsby site.

```
gatsby clean & gatsby build
[1] 84360
info Deleting .cache, public
info Successfully deleted directories
[1]  + 84360 done       gatsby clean
success open and validate gatsby-configs - 0.724s
success load plugins - 0.684s
success onPreInit - 0.010s
success delete html and css files from previous builds - 0.016s
success initialize cache - 0.025s
success copy gatsby files - 0.061s
success onPreBootstrap - 0.005s
success createSchemaCustomization - 0.007s

 ERROR #11321  PLUGIN

"gatsby-source-storyblok" threw an error while running the sourceNodes lifecycle:

Parse Error

  Error: Parse Error

  - stream_base_commons.js:145 TLSWrap.onStreamRead
    internal/stream_base_commons.js:145:17


not finished source and transform nodes - 5.281s
```

This happen only when I add a specific relation to resolve called `launch_case_study.case_studyt` that is identical to the `launch_insight.insight`. 

Both are a single-option story selectors and they only change in the path of the story to choose from.

<img width="1129" alt="Schermata 2019-11-20 alle 18 49 36" src="https://user-images.githubusercontent.com/20659387/69265644-e239eb00-0bc9-11ea-9697-7cdbf171a38b.png">

Any idea why?

Thank you

**Comment by schabibi1** [comment]
@michelesketchin It's been a while since we had communication on this issue, so I'll close this issue for now. But let me know/feel free to re-open this issue if you still face this issue.
