### ISSUE TITLE
Provide a way to retrieve different releases from a branch

### ISSUE THREAD

**Issue by sharanrprasad** [storyblok/gatsby-source-storyblok#17]
The storyblok documentation mentions adding a `from_release` parameter to the url to retrieve a story from a particular release. Can you please provide the same option as part of this plugin.

**Comment by sharanrprasad** [comment]
Can you guys please help with this?

**Comment by samuells** [comment]
Hi Sharan. Thanks for your input and I am sorry for the late response. I will check this with our dev team and let you know asap.

**Comment by sharanrprasad** [comment]
@samuells Any news on this?

**Comment by tlambrou** [comment]
@samuells any update?

> Hi Sharan. Thanks for your input and I am sorry for the late response. I will check this with our dev team and let you know asap.

**Comment by samuells** [comment]
Oh yes. This should answer your question https://www.storyblok.com/faq/how-to-access-an-edited-version-of-a-story-from-a-release ... @sharanrprasad sorry I missed this thread. 🙏🏼

**Comment by samuells** [comment]
Also from docs of Delivery Api - https://www.storyblok.com/docs/api/content-delivery#core-resources/stories/retrieve-one-story you should be able to add the `from_release` parameter to payload of the request.

from_release | Access version of specific release by release id
-- | --

**Comment by tlambrou** [comment]
@samuells none of these apis are accessible in the `gatsby-source-storyblok` config.  If we want to build from the release data we are not able to do so at present.

**Comment by samuells** [comment]
I am not sure if I understand correctly. There is not a special API for the releases. All you need to do is to set up the `from_release` parameter in the request. 

Check out the docs where is the sample with the preview. 
https://www.storyblok.com/docs/guide/in-depth/content-authoring#releases-app

> The content of a release can be accessed from the Content Delivery API using the draft token and appending the parameter from_release with the release id. In the following example, you can see how to get the Story of Home with id 29 in the draft version.

```
curl -X GET \
'https://api.storyblok.com/v1/cdn/stories/home?from_release=29&version=draft&token=miQeEopSce7bklQFVbBozQtt'
```

**Comment by iamfortune** [comment]
Closing this issue as it seems @samuells answered this question. Feel free to open it again @sharanrprasad.
