### ISSUE TITLE
How do I get all tags?

### ISSUE THREAD

**Issue by RobinBroocks** [storyblok/gatsby-source-storyblok#18]
Hi,
I'm trying to get a list of all tags via graphQL, but when I try I only get one tag as a result.

```
allStoryblokTag {
  edges {
    node {
      name
      taggings_count
    }
  }
}
```

I also tried getting the tags with the content delivery API but there I got an empty array as a result.

```
Storyblok.get('cdn/tags/', {
  "starts_with": "posts/",
  "token": process.env.GATSBY_STORYBLOK_TOKEN,
  })
  .then(response => {
    console.log(response)
  }).catch(error => {
    console.log(error)
  })
```

I did the same thing as in the [documentation](https://www.storyblok.com/docs/api/content-delivery#core-resources/tags/retrieve-all-tags).

Any idea what I did wrong?

Thank you.

**Comment by emanuelgsouza** [comment]
Hi, thanks for submitting this issue and sorry for the delay. It was implemented a fix! Waiting for reviewing and merging.

**Comment by emanuelgsouza** [comment]
The fix is already published. Take a look on the [v1.1.0](https://github.com/storyblok/gatsby-source-storyblok/releases/tag/v1.1.0) version.
