### ISSUE TITLE
Compatibility with Gatsby v5

### ISSUE THREAD

**Issue by yvonnetangsu** [storyblok/gatsby-source-storyblok#192]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

---

## Expected Behavior

Gatsby v5 has been out since Nov 2022. Currently, `gatsby-source-storyblok` doesn't officially support Gatsby v5 but would be great if it does.

## Current Behavior

`gatsby-source-storyblok` requires installation with the `--legacy-peer-deps` npm flag or override to work with Gatsby 5

## Steps to Reproduce

1. Set up a repo with the Gatsby v5 starter
2. Try to install gatsby-source-storyblok without the --legacy-peer-deps flag
3. See errors

**Comment by schabibi1** [comment]
Hi @yvonnetangsu 

It's a work in progress to upgrade gatsby-source-storyblok. Please expect there will be an update about that.
In short, Gatsby's [Partial Hydration](https://www.gatsbyjs.com/docs/conceptual/partial-hydration) includes React Server Components. Our visual editor needs client-side configs as we use hooks for loading the JS Bridge.

**Comment by yvonnetangsu** [comment]
Awesome. Thank you for the update @schabibi1 ! Glad to know it's in the works.

**Comment by alex-mcgovern** [comment]
FYI I am running `gatsby-source-storyblok` with Gatsby v5 using `--legacy-peer-deps` flag and it works. 

As I understand it from this thread, there is work required to update the hooks & methods for working with Storyblok editor — we don't actually use these, we just use this plugin as a source plugin. 

It would be great if the gatsby deps could be upgraded so we don't have to use the legacy peer deps flag to install.

I think longer term, it would be worthwhile to consider seperating the concerns of sourcing the data from the storyblok (what this plugin says it does) and providing the handles to work with the data in the visual editor.

**Comment by yvonnetangsu** [comment]
Agree with what @alex-mcgovern said. Is it possible for the gatsby deps be updated first in the meantime while we wait for the larger update to the visual editor related things, @schabibi1?

**Comment by jclark-vanish** [comment]
I am having an issue getting draft content from the visual editor, I have it set to use draft version in gatsby-config.js. I can see the draft json file looks correct.  Would this issue have anything to do with that?

**Comment by schabibi1** [comment]
Upgrading Gatsby dependencies to Gatsby 5 will happen relatively soon as I have solid info confirmed internally.
Gatsby 5 uses [React Server Components](https://react.dev/blog/2023/03/22/react-labs-what-we-have-been-working-on-march-2023#react-server-components) for users who want to use [Partial Hydration](https://www.gatsbyjs.com/docs/conceptual/partial-hydration). It breaks visual editor behaviors from what we tested to upgrade our [React SDK](https://github.com/storyblok/storyblok-react).

Gatsby SDK imports our [React SDK](https://github.com/storyblok/storyblok-react) and it was the blocker. But I'm happy to tell you the communication will happen quite soon and Gatsby SDK will be able to adopt RSC support which Gatsby 5 uses for [Partial Hydration](https://www.gatsbyjs.com/docs/conceptual/partial-hydration).

**Comment by yvonnetangsu** [comment]
That's wonderful news @schabibi1 ! 🎉  Thanks for the update.

**Comment by rasmusbe** [comment]
Any news regarding this @schabibi1 ? ❤️

**Comment by schabibi1** [comment]
@rasmusbe As we announced just recently our React SDK now supports RSC, gatsby-source-storyblok will follow RSC support which is necessary for upgrading to Gatsby 5.
[https://dev.to/storyblok/storyblok-react-sdk-now-supports-react-server-components-1hk6](https://dev.to/storyblok/storyblok-react-sdk-now-supports-react-server-components-1hk6)

We're testing Partial Hydration as it includes RSC and once we confirm, we can release Gatsby 5 supported version of gatsby-source-storyblok.

**Comment by schabibi1** [comment]
We released Gatsby 5 supported gatsby-source-storyblok v6.0.0. #327 
Communication through updated README, announcement on Discord, announcement article, and update Ultimate Tutorial series will happen upcoming days.

Thank you for everyone being patient and we're glad to tell this news first with you.

**Comment by yvonnetangsu** [comment]
Thanks for the update @schabibi1! Great news.
