### ISSUE TITLE
How to use api parameter "resolve_links"

### ISSUE THREAD

**Issue by fcisio** [storyblok/gatsby-source-storyblok#21]
Hi, I'm fairly new to this plugin and Storyblok. I'm trying to use translated slugs, which requires ["resolve_links"](https://www.storyblok.com/cl/improved-translated-slugs)

Is there a way to use this parameter with this plugin? If so any pointers on how to do it would be greatly appreciated.

Thanks.

**Comment by DominikAngerer** [comment]
Hey there!

We've added the option in the readme.md - if you have futher issues feel free to catch us on the live chat if you did not already do that :)

Best
Dom
