### ISSUE TITLE
Error after adding library to repo and running gatsby develop

### ISSUE THREAD

**Issue by IgorPodlawski** [storyblok/gatsby-source-storyblok#27]
Hi!

I'm getting error after adding gatsby-source-storyblok to my repo and running gatsby develop.

**Error message:**
> Error: Cannot find module 'core-js/modules/es6.regexp.split'

This is probably related to Babel changes:
https://github.com/facebook/jest/issues/8476#issuecomment-494124876 

After downgrading core-js dependency from 3.6.5 to 2.6.5 everything works fine in my website repo.

**Comment by BrieucKyo** [comment]
Same error message here!
Downgrading core-js to 2.6.5 will fix this error but creates unrelated errors on others gatsby plugins.

**Comment by heresandyboy** [comment]
Hi, this issue is also directly affecting the gatsby-storyblok-boilerplate and an issue has been raised here [ #12](https://github.com/storyblok/gatsby-storyblok-boilerplate/issues/12)

I've added some comments there.

**Comment by heresandyboy** [comment]
This issue is now fixed and released in gatsby-source-storyblok v1.0.0 😁

@emanuelgsouza  we can close this issue now thanks for merging my changes! 👌

**Comment by emanuelgsouza** [comment]
Great! Thanks for your PR!
