### ISSUE TITLE
Dynamic Images for Gatsby 

### ISSUE THREAD

**Issue by nicolekbaird** [storyblok/gatsby-source-storyblok#271]
We have run into an issue while trying to update our site to the latest Gatsby version utilizing gatsby-source-storyblok. We would like to utilize the latest gatsby-image-plugin to serve our images from Storyblok. The [documentation](https://www.storyblok.com/tp/gatsby-image) provided by Storyblok gives a simple use case, but in the documentation provided, it only gives the example of Querying for an image when the name of the image is known. We need to conditionally render our images based on page. 

For example, our Hero Block is used across several pages and we want to conditionally render the image used in the Hero based on the page and the image uploaded for that page in Storyblok.

Our thought was that we should be able to query in storyblokEntry at the page level to source the images used on that page. While we can find the image URL within the storyblokEntry graphql query, the childImageSharp --> gatsbyImageData object needed for dynamic images in gatsby-image-plugin seems to only be available on the allFile query. If the gatsbyImageData object is only available on allFiles, we don't see a way to conditionally render images without querying all images in Storyblok using gatsby-node and matching them at the component level. This however will not work as it causes the size of context shared to be too large to even deploy on Netlify. 

I am sure majority of people who use Storyblok with Gatsby need to conditionally render images. We have been sent to [this plug-in](https://github.com/bejamas/gatsby-storyblok-image) as an option but it also isn't compatible with newer versions of Gatsby. Many other CMS's have already created native support for the latest Gatsby-Image-Plugin, which can be seen [here](https://www.gatsbyjs.com/docs/how-to/images-and-media/using-gatsby-plugin-image/) in this Gatsby documentation page. We'd love for this to be a feature of gatsby-source-storyblok!

**Comment by schabibi1** [comment]
@nicolekbaird Thanks for sharing your DX with us after following our [Gatsby Image tutorial](https://www.storyblok.com/tp/gatsby-image).
I'd like to share with you [this approach](https://discord.com/channels/700316478792138842/700326489731891201/1042526760039890944) shared by one of our active users on Discord.

I understand your point that implementing the Gatsby Image feature into to our SDK might align with other CMSs Gatsby plugins.
But when Storyblok already has a way to achieve the same goal without implementing all new Gatsby features, it might not be necessary in this case to implement.

Also, by creating a custom image component in Storyblok covers the webp & image size generation and compression through Storyblok Content Delivery API.

**Comment by nicolekbaird** [comment]
***@***.*** is inviting you to a scheduled Zoom meeting.

Topic: Website Catchup
Time: Aug 16, 2023 11:00 AM Pacific Time (US and Canada)

Join Zoom Meeting
https://avenues.zoom.us/j/96493351797

Meeting ID: 964 9335 1797

---

One tap mobile
+15074734847,,96493351797# US
+15642172000,,96493351797# US

---

Dial by your location
• +1 507 473 4847 US
• +1 564 217 2000 US
• +1 646 558 8656 US (New York)
• +1 646 931 3860 US
• +1 669 444 9171 US
• +1 669 900 6833 US (San Jose)
• +1 689 278 1000 US
• +1 719 359 4580 US
• +1 253 205 0468 US
• +1 253 215 8782 US (Tacoma)
• +1 301 715 8592 US (Washington DC)
• +1 305 224 1968 US
• +1 309 205 3325 US
• +1 312 626 6799 US (Chicago)
• +1 346 248 7799 US (Houston)
• +1 360 209 5623 US
• +1 386 347 5053 US
• 833 928 4610 US Toll-free
• 877 853 5257 US Toll-free
• 888 475 4499 US Toll-free
• 833 548 0276 US Toll-free
• 833 548 0282 US Toll-free
• 833 928 4608 US Toll-free
• 833 928 4609 US Toll-free

Meeting ID: 964 9335 1797

Find your local number: https://avenues.zoom.us/u/aezpMc69SP

---

Join by SIP
• ***@***.***

---

Join by H.323
• 162.255.37.11 (US West)
• 162.255.36.11 (US East)
• 115.114.131.7 (India Mumbai)
• 115.114.115.7 (India Hyderabad)
• 213.19.144.110 (Amsterdam Netherlands)
• 213.244.140.110 (Germany)
• 103.122.166.55 (Australia Sydney)
• 103.122.167.55 (Australia Melbourne)
• 149.137.40.110 (Singapore)
• 64.211.144.160 (Brazil)
• 149.137.68.253 (Mexico)
• 69.174.57.160 (Canada Toronto)
• 65.39.152.160 (Canada Vancouver)
• 207.226.132.110 (Japan Tokyo)
• 149.137.24.110 (Japan Osaka)

Meeting ID: 964 9335 1797
