### ISSUE TITLE
Upgrading Dependencies

### ISSUE THREAD

**Issue by tlambrou** [storyblok/gatsby-source-storyblok#30]
Can you guys please upgrade the dependencies on this plugin?

Version of gatsby used in this library requires `core-js@2` which is no longer supported and fills my console with warnings.

Also the peer dependency of `storyblok-react` is using version `0.0.6` instead of the latest `0.0.10`

**Comment by emanuelgsouza** [comment]
Hi, thanks for submitting this issue. You can check the latest version [v1.0.0](https://github.com/storyblok/gatsby-source-storyblok/releases/tag/v1.0.0). We upgraded the `storyblok-js-client` and `storyblok-react` packages.
