### ISSUE TITLE
getStories returns "any" type

### ISSUE THREAD

**Issue by joakimmillen** [storyblok/gatsby-source-storyblok#347]
### Describe the issue you're facing

When upgrading the library to version `^6.0.0` the type returned from `getStories` is any rather than ISbStories. 

### Reproduction

https://github.com/joakimmillen/gatsby-source-storyblok-type-issue

### Steps to reproduce

- Open index.ts
- check the type of the `response` variable
- is "any" should be "ISbStories"

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 10.25 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
    pnpm: 8.3.1 - ~/.nvm/versions/node/v18.12.1/bin/pnpm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.4
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by schabibi1** [comment]
@joakimmillen Sorry for the late reply, if you face a quite huge blocker because of this issue you created, please feel free to re-open this issue. Otherwise, I'll close it for now as it's not the bug that needs a hot fix.
