### ISSUE TITLE
Resolve Links in Editor.js

### ISSUE THREAD

**Issue by aidenBarrett96** [storyblok/gatsby-source-storyblok#36]
I am trying to get all data about a linked story but only get the overview data (uuid, cached_url). Is there a way to resolve links with the Storyblok bridge to get this type of data into the visual editor.

**Comment by tlambrou** [comment]
@aidenBarrett96 you should be able to achieve this by passing `resolve_links` into the requests in editor.js.  The `resolveLinks` key is only for `gatsby-source-storyblok` config.

```
  loadStory(payload) {
    const path = window.storyblok.getParam('path')
    window.storyblok.get(
      {
        slug: path,
        version: 'draft',
        resolve_links: sbConfig.options.resolveLinks || 'url',
        resolve_relations: sbConfig.options.resolveRelations || [],
      },
      (data) => {
        this.setState({ story: data.story })
      }
    )
  }
```

https://www.storyblok.com/docs/api/content-delivery#core-resources/stories/retrieve-multiple-stories

**Comment by iamfortune** [comment]
Hi @aidenBarrett96, I will be closing this issue, feel free to open it in the future if you need to.
