### ISSUE TITLE
Use with Incremental Builds possible?

### ISSUE THREAD

**Issue by pedrosousa13** [storyblok/gatsby-source-storyblok#37]
Would using the new incremental builds [Gatsby Incremental Builds](https://www.gatsbyjs.com/cloud/docs/incremental-builds/) bring any benefit to the speed of the build with this plugin?

**Comment by kik-o** [comment]
Bumping this

**Comment by kik-o** [comment]
Javascript doesn't load when incremental deploys are enabled for some builds

**Comment by iamfortune** [comment]
Closing this issue as I think @kik-o already answered this. Feel free to reopen it if you want more discussion on it.
