### ISSUE TITLE
Can we add "component" as one of the fields we can access? 

### ISSUE THREAD

**Issue by joepalomino** [storyblok/gatsby-source-storyblok#4]

**Comment by onefriendaday** [comment]
Actually you can access all content under the "content" field. This includes component. You do you mean filtering?

**Comment by DominikAngerer** [comment]
Adding `component` to the item itself in a non stringified version is what I guess would be the idea you had. 

What about adding the whole `content` as `original_content` to preserve the possible option to query on that but still have access the the stringified version?

**Comment by onefriendaday** [comment]
Its now available in version 0.2.0:
https://github.com/storyblok/gatsby-source-storyblok#filtering-on-content-type-fields
