### ISSUE TITLE
full_slug is missing from alternates

### ISSUE THREAD

**Issue by marcosmesser** [storyblok/gatsby-source-storyblok#54]
When querying `allStoryblokEntries`, `full_slug` is not returned in `alternates` anymore, only `slug`.

**Comment by schabibi1** [comment]
Hi @marcosmesser , thank you for letting us know, and thank you for reaching out.
Could you share with us the information below?

- Your GraphQL data layer path to fetch `full_slug` 
- Is it filtered to get all items from a news folder?
- Is it filtered for a specific language using following query?
- Is it filtered on content type fields?

**Comment by marcosmesser** [comment]
Hi @schabibi1 , thanks for looking into it.

Seems like from when I last tested and opened the issue, something changed on the backend.

At the time, `full_slug` wouldn't even show up as an option in Gatsby's GraphiQL. Now it appears as the first one, whilst everything else is alphabetically sorted.

Anyway, we can close this one.

**Comment by schabibi1** [comment]
Hi @marcosmesser 
Happy to hear that `full_slug` appears now! Thank you for describing the details and closing this issue.
