### ISSUE TITLE
Links inside a richtext field don't get resolved

### ISSUE THREAD

**Issue by xylophonehero** [storyblok/gatsby-source-storyblok#57]
Hey Storyblok team. Noticed this bug earlier.

For internal links I've created in a rich text field, whether they are an inline link or a custom block containing a link, they don't the usual storyblok link object containing the full_slug when using resolve_links=url.

This link has resolved. It is part of a block on a content type not inside a rich text field
![image](https://user-images.githubusercontent.com/68996622/125957805-177f7bc9-3cbd-4962-a06a-08e5b443e5ed.png)

But this link hasn't resolved. It is part of a rich text fields
![image (1)](https://user-images.githubusercontent.com/68996622/125958051-b2347124-d5b2-4006-952a-3ef9a3960e2e.png)

Thanks for any help you can give.

**Comment by schabibi1** [comment]
@xylophonehero Does [this new release](https://github.com/storyblok/storyblok-js#2-listen-to-storyblok-visual-editor-events) support for `resolve_links` help?
Our gatsby-source-storyblok includes the dependency from storyblok-js SDK, so it should apply the change.

Please feel free to reopen this issue if you still face the same issue/another issue.
