### ISSUE TITLE
Sourcing from multiple spaces

### ISSUE THREAD

**Issue by samlogan** [storyblok/gatsby-source-storyblok#69]
Hey Storyblok, is it possible or are you planning on making it possible to source from multiple spaces? We have a client with two spaces, one's a microservice that's powering part of their application (this is preexisting and bloated) and the other is new and purely for marketing content.

**Comment by schabibi1** [comment]
@samlogan I'm not sure if it's relevant to gatsby-source-storyblok. It sounds more relevant to our sync content, etc between multiple spaces. Let us know if [this tutorial](https://www.storyblok.com/tp/multi-space-setup-cli) will help you with our CLI examples.
